### ISSUE TITLE
problems里边的题提交后网页崩溃，safari和chrome都试过了

### ISSUE THREAD

**Issue by HalveLuve** [aiedbnu/bnuoj#9]
如题，挂了内网，用的c和c++，一提交网页就崩溃。
<img width="1266" alt="截屏2020-09-28 下午6 19 50" src="https://user-images.githubusercontent.com/20919559/94420844-4e588880-01b7-11eb-954e-60b1928a394b.png">
<img width="1661" alt="截屏2020-09-28 下午6 20 21" src="https://user-images.githubusercontent.com/20919559/94420871-587a8700-01b7-11eb-975c-9d0558bb5749.png">

**Comment by yofn** [comment]
![image](https://user-images.githubusercontent.com/3108764/94633894-31c86780-0301-11eb-9fcc-35de8bc99983.png)
问题复现

**Comment by yofn** [comment]
http://oj.bnu.edu.cn/problem/aplusb/submit

**Comment by yofn** [comment]
暂时没有明确问题原因是什么？
+ 连接不稳定?
+ 代码提交失败? 代码有约束?

**Comment by yofn** [comment]
原因确认：安全设备阻断请求造成，已解决
